spring:
  datasource:
#    url: jdbc:mysql://betterus-db.cnomvwmqhkiv.ap-northeast-2.rds.amazonaws.com:3306/betterus
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:tcp://localhost/~/test2
    username: sas
    password: 12
    driver-class-name: org.h2.Driver

  profiles:
    active: local

  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #          show_sql: true
        format_sql: true
  # Naver smtp server 사용
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: nicednjsdud@naver.com #네이버 아이디
    password: dnjsdud123! #네이버 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            #trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면
    servlet:
      multipart:
        maxFileSize: 10MB
        maxRequestSize: 20MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: /static/**
server:
  port : 8080